name: Every Minute POST Request

on:
  schedule:
    - cron: "*/1 * * * *" # Triggers every minute

jobs:
  post-request:
    runs-on: ubuntu-latest

    steps:
    - name: Send POST Request
      env:
        TARGET_URL: https://webhook.site/0148c074-6680-43a5-9f23-5eb28229ac3c
      run: |
        curl -X POST "$TARGET_URL" \
          -H "Content-Type: application/json" \
          -d '{"message": "hello"}'
